--CREATE SEQUENCE IF NOT EXISTS USERS_ID_SEQ;
--CREATE SEQUENCE IF NOT EXISTS ROOMS_ID_SEQ;
--CREATE SEQUENCE IF NOT EXISTS BOOKINGS_ID_SEQ;

INSERT INTO USERS (ID, LOGIN, NAME, PASSWORD, SURNAME) VALUES (USERS_ID_SEQ.NEXTVAL, 'jsmith', 'John', 'qwerty', 'Smith');
INSERT INTO USERS (ID, LOGIN, NAME, PASSWORD, SURNAME) VALUES (USERS_ID_SEQ.NEXTVAL, 'jdoe', 'Jane', 'mySecret', 'Doe');

INSERT INTO ROOMS (ID, LOCATION, ROOMNAME, PHONE, PROJECTOR, SEATS) VALUES (ROOM_ID_SEQ.NEXTVAL, '1st floor', 'Large Room', '22-22-22-22', TRUE, 10);
INSERT INTO ROOMS (ID, LOCATION, ROOMNAME, PHONE, PROJECTOR, SEATS) VALUES (ROOM_ID_SEQ.NEXTVAL, '1st floor', 'Medium Room', null, TRUE, 6);
INSERT INTO ROOMS (ID, LOCATION, ROOMNAME, PHONE, PROJECTOR, SEATS) VALUES (ROOM_ID_SEQ.NEXTVAL, '2nd floor', 'Small Room', null, FALSE, 4);